
import React from 'https://aistudiocdn.com/react@^19.2.0';
import { Page, Text, View, Document, StyleSheet, Font, pdf } from 'https://esm.sh/@react-pdf/renderer@4.1.6?bundle&external=react,react-dom';

// Types are imported solely for type checking in the worker context
// Ensure paths match your project structure
import { TranscriptEntry, Card, QuizQuestion } from './types';

// Register Font (Must be done inside the worker)
Font.register({
  family: 'NotoSansJP',
  src: 'https://cdn.jsdelivr.net/npm/@fontsource/noto-sans-jp@5.0.19/files/noto-sans-jp-japanese-400-normal.woff',
  format: 'woff'
});

const styles = StyleSheet.create({
  page: {
    padding: 30,
    fontFamily: 'NotoSansJP',
    fontSize: 10,
    color: '#333',
  },
  header: {
    marginBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#ccc',
    paddingBottom: 10,
  },
  title: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 5,
  },
  subtitle: {
    fontSize: 10,
    color: '#666',
  },
  section: {
    marginBottom: 15,
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: 'bold',
    marginBottom: 8,
    marginTop: 10,
    backgroundColor: '#f0f0f0',
    padding: 4,
  },
  entryContainer: {
    marginBottom: 10,
  },
  englishText: {
    fontSize: 11,
    marginBottom: 2,
    lineHeight: 1.4,
  },
  japaneseText: {
    fontSize: 9,
    color: '#555',
    marginBottom: 2,
    lineHeight: 1.4,
  },
  explanationText: {
    fontSize: 8,
    color: '#666',
    marginLeft: 8,
    paddingLeft: 8,
    borderLeftWidth: 1,
    borderLeftColor: '#ddd',
    lineHeight: 1.3,
    whiteSpace: 'pre-wrap',
  },
  wordRow: {
    flexDirection: 'row',
    borderBottomWidth: 0.5,
    borderBottomColor: '#eee',
    paddingVertical: 4,
  },
  wordFront: {
    width: '30%',
    fontWeight: 'bold',
  },
  wordBack: {
    width: '70%',
  },
  quizContainer: {
    marginBottom: 10,
    padding: 8,
    backgroundColor: '#fafafa',
    borderWidth: 0.5,
    borderColor: '#eee',
  },
  quizQuestion: {
    fontSize: 10,
    marginBottom: 5,
    fontWeight: 'bold',
  },
  quizChoice: {
    fontSize: 9,
    marginLeft: 10,
    marginBottom: 2,
  },
});

// PDF Document Component (Moved from Modal to Worker)
const MyDocument: React.FC<{
  title: string;
  transcript: TranscriptEntry[];
  words: Card[];
  quizQuestions: QuizQuestion[];
  options: {
    english: boolean;
    japanese: boolean;
    explanation: boolean;
    wordList: boolean;
    quiz: boolean;
  };
}> = ({ title, transcript, words, quizQuestions, options }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <View style={styles.header}>
        <Text style={styles.title}>{title}</Text>
        <Text style={styles.subtitle}>Generated by Audio-Sync Reader</Text>
      </View>

      {/* Transcript Section */}
      {(options.english || options.japanese || options.explanation) && transcript.length > 0 && (
        <View style={styles.section}>
          {transcript.map((entry, i) => (
            <View key={i} wrap={false} style={styles.entryContainer}>
              {options.english && (
                <Text style={styles.englishText}>{entry.english}</Text>
              )}
              {options.japanese && entry.japanese && (
                <Text style={styles.japaneseText}>{entry.japanese}</Text>
              )}
              {options.explanation && entry.explanation && (
                <Text style={styles.explanationText}>{entry.explanation.replace(/__PERSONA_PROFILE__[\s\S]*?__END_PERSONA__/, '').replace(/__BACKGROUND_INFO__[\s\S]*?__END_BACKGROUND__/, '').trim()}</Text>
              )}
            </View>
          ))}
        </View>
      )}

      {/* Word List Section */}
      {options.wordList && words.length > 0 && (
        <View break>
          <Text style={styles.sectionTitle}>Word List</Text>
          {words.map((word, i) => (
            <View key={i} style={styles.wordRow} wrap={false}>
              <Text style={styles.wordFront}>{word.front}</Text>
              <Text style={styles.wordBack}>
                {word.back} {word.pronunciation ? `[${word.pronunciation}]` : ''}
              </Text>
            </View>
          ))}
        </View>
      )}

      {/* Quiz Section */}
      {options.quiz && quizQuestions.length > 0 && (
        <View break>
          <Text style={styles.sectionTitle}>Quiz</Text>
          {quizQuestions.map((q, i) => (
            <View key={i} style={styles.quizContainer} wrap={false}>
              <Text style={styles.quizQuestion}>Q{i + 1}. {q.question}</Text>
              {q.choices.map((c, ci) => (
                <Text key={ci} style={styles.quizChoice}>
                  {String.fromCharCode(65 + ci)}. {c}
                </Text>
              ))}
            </View>
          ))}
          <View break>
             <Text style={styles.sectionTitle}>Quiz Answers</Text>
             {quizQuestions.map((q, i) => (
                 <Text key={i} style={{fontSize: 9, marginBottom: 2}}>
                     Q{i+1}: {String.fromCharCode(65 + q.correctAnswerIndex)}
                 </Text>
             ))}
          </View>
        </View>
      )}
    </Page>
  </Document>
);

// Worker Message Handler
self.onmessage = async (e: MessageEvent) => {
    const { title, transcript, words, quizQuestions, options } = e.data;

    try {
        const blob = await pdf(
            <MyDocument 
                title={title} 
                transcript={transcript} 
                words={words} 
                quizQuestions={quizQuestions} 
                options={options} 
            />
        ).toBlob();
        
        self.postMessage({ type: 'success', blob });
    } catch (error: any) {
        console.error("Worker PDF generation failed:", error);
        self.postMessage({ type: 'error', message: error.message || 'Unknown error' });
    }
};
