
export const WORKER_CODE = `
import React from 'https://esm.sh/react@18.3.1';
import { Page, Text, View, Document, StyleSheet, Font, pdf } from 'https://esm.sh/@react-pdf/renderer@4.1.6?bundle&external=react,react-dom';

Font.register({
  family: 'NotoSansJP',
  src: 'https://cdn.jsdelivr.net/npm/@fontsource/noto-sans-jp@5.0.19/files/noto-sans-jp-japanese-400-normal.woff',
  format: 'woff'
});

const styles = StyleSheet.create({
  page: { padding: 30, fontFamily: 'NotoSansJP', fontSize: 10, color: '#333' },
  header: { marginBottom: 20, borderBottomWidth: 1, borderBottomColor: '#ccc', paddingBottom: 10 },
  title: { fontSize: 18, fontWeight: 'bold', marginBottom: 5 },
  subtitle: { fontSize: 10, color: '#666' },
  section: { marginBottom: 15 },
  sectionTitle: { fontSize: 12, fontWeight: 'bold', marginBottom: 8, marginTop: 10, backgroundColor: '#f0f0f0', padding: 4 },
  entryContainer: { marginBottom: 10 },
  englishText: { fontSize: 11, marginBottom: 2, lineHeight: 1.4 },
  japaneseText: { fontSize: 9, color: '#555', marginBottom: 2, lineHeight: 1.4 },
  explanationText: { fontSize: 8, color: '#666', marginLeft: 8, paddingLeft: 8, borderLeftWidth: 1, borderLeftColor: '#ddd', lineHeight: 1.3, whiteSpace: 'pre-wrap' },
  wordRow: { flexDirection: 'row', borderBottomWidth: 0.5, borderBottomColor: '#eee', paddingVertical: 4 },
  wordFront: { width: '30%', fontWeight: 'bold' },
  wordBack: { width: '70%' },
  quizContainer: { marginBottom: 10, padding: 8, backgroundColor: '#fafafa', borderWidth: 0.5, borderColor: '#eee' },
  quizQuestion: { fontSize: 10, marginBottom: 5, fontWeight: 'bold' },
  quizChoice: { fontSize: 9, marginLeft: 10, marginBottom: 2 }
});

const MyDocument = ({ title, transcript, words, quizQuestions, options }) => {
  return React.createElement(Document, {},
    React.createElement(Page, { size: 'A4', style: styles.page },
      React.createElement(View, { style: styles.header },
        React.createElement(Text, { style: styles.title }, title),
        React.createElement(Text, { style: styles.subtitle }, 'Generated by Audio-Sync Reader')
      ),
      (options.english || options.japanese || options.explanation) && transcript.length > 0 &&
      React.createElement(View, { style: styles.section },
        transcript.map((entry, i) => 
          React.createElement(View, { key: i, wrap: false, style: styles.entryContainer },
            options.english && React.createElement(Text, { style: styles.englishText }, entry.english),
            options.japanese && entry.japanese && React.createElement(Text, { style: styles.japaneseText }, entry.japanese),
            options.explanation && entry.explanation && React.createElement(Text, { style: styles.explanationText }, 
               entry.explanation.replace(/__PERSONA_PROFILE__[\\s\\S]*?__END_PERSONA__/, '').replace(/__BACKGROUND_INFO__[\\s\\S]*?__END_BACKGROUND__/, '').trim()
            )
          )
        )
      ),
      options.wordList && words.length > 0 &&
      React.createElement(View, { break: true },
        React.createElement(Text, { style: styles.sectionTitle }, 'Word List'),
        words.map((word, i) => 
           React.createElement(View, { key: i, style: styles.wordRow, wrap: false },
             React.createElement(Text, { style: styles.wordFront }, word.front),
             React.createElement(Text, { style: styles.wordBack }, 
               word.back + (word.pronunciation ? ' [' + word.pronunciation + ']' : '')
             )
           )
        )
      ),
      options.quiz && quizQuestions.length > 0 &&
      React.createElement(View, { break: true },
         React.createElement(Text, { style: styles.sectionTitle }, 'Quiz'),
         quizQuestions.map((q, i) => 
            React.createElement(View, { key: i, style: styles.quizContainer, wrap: false },
               React.createElement(Text, { style: styles.quizQuestion }, 'Q' + (i + 1) + '. ' + q.question),
               q.choices.map((c, ci) => 
                  React.createElement(Text, { key: ci, style: styles.quizChoice }, 
                     String.fromCharCode(65 + ci) + '. ' + c
                  )
               )
            )
         ),
         React.createElement(View, { break: true },
            React.createElement(Text, { style: styles.sectionTitle }, 'Quiz Answers'),
            quizQuestions.map((q, i) => 
               React.createElement(Text, { key: i, style: {fontSize: 9, marginBottom: 2} },
                  'Q' + (i + 1) + ': ' + String.fromCharCode(65 + q.correctAnswerIndex)
               )
            )
         )
      )
    )
  );
};

self.onmessage = async (e) => {
  const { title, transcript, words, quizQuestions, options } = e.data;
  try {
    const blob = await pdf(React.createElement(MyDocument, { title, transcript, words, quizQuestions, options })).toBlob();
    self.postMessage({ type: 'success', blob });
  } catch (error) {
    self.postMessage({ type: 'error', message: error.message });
  }
};
`;
